# Generated by Django 2.2.16 on 2022-06-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titlccse',
        ),
    ]
